# semi_dynamic_objects

semi_dynamic_objects:
  - name: trash_can
    r: 0.0
    g: 1.0
    b: 0.0

  - name: chair
    r: 1.0
    g: 0.5
    b: 0.5

  - name: bench
    r: 1.0
    g: 0.0
    b: 0.0

  - name: table
    r: 0.5
    g: 0.5
    b: 0.0